name: Build

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      lint:
        required: false
        type: boolean
        default: false
      build:
        required: true
        type: boolean
      config:
        required: false
        type: string
        default: Release
      tests:
        required: false
        type: string
        default: "./test/run_tests.sh"
      shell:
        required: false
        type: string
        default: bash
      llvm_version:
        required: false
        type: string
        default: master
      enable_asan:
        required: false
        type: string
        default: OFF
        
jobs:
  build:
    defaults:
      run:
        shell: ${{ inputs.shell }}

    runs-on: ${{ inputs.os }}
    steps:
    
    - name: Configure git
      run: |
        git config --global core.symlinks true
        git config --global core.autocrlf input
          
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        
    - name: Install dependencies
      run: | 
        sudo apt-get update -y
        sudo apt-get install -y clang-format --no-install-recommends
      if: ${{ inputs.lint }}
      
    - name: Run clang-format
      run: ONLY_CHECK=1 ./run-clang-format.sh
      if: ${{ inputs.lint }}

    - name: Ccache
      uses: hendrikmuhs/ccache-action@v1.2.17
      with:
        key: ${{ runner.os }}-${{ inputs.config }}-${{ inputs.llvm_version }}
      if: ${{ inputs.build }}

    - name: Build
      run: ./build.sh
      env:
        BUILD_TYPE: ${{ inputs.config }}
        ENABLE_ASAN: ${{ inputs.enable_asan }}
        LLVM_VERSION: ${{ inputs.llvm_version }}
      if: ${{ inputs.build }}
