name: build

on:
  push:
     branches-ignore:
      - 'dependabot**'
  pull_request:
    branches-ignore:
      - 'dependabot**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    defaults:
      run:
        shell: bash
        
    runs-on: ubuntu-latest
    steps:
    
    - name: Configure git
      run: |
          git config --global core.symlinks true
          git config --global core.autocrlf input
          
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        
    - name: Install dependencies
      run: | 
        sudo apt-get update -y
        sudo apt-get install -y clang-format --no-install-recommends
      
    - name: Run clang-format
      run: |
        ls
        ./run-clang-format.sh
